### PR TITLE
Added getRangeViewAsync & try to add options for view

### PR DESCRIPTION
**Pull request by goatandsheep**
Can this be merged?

### CODE REVIEW

**Comment by frank-dspeed** [comment]
@goatandsheep 
https://github.com/balassy/couchbase-promise/pull/14

visit the url and Correct this pull reqest here plz

**Comment by goatandsheep** [comment]
I'm taking a look at it. I think it might have just been the last commit, the version change. I know you tried to do the version change, but for some reason, travisci is not liking that.

**Comment by goatandsheep** [comment]
I'm pretty busy on something else right now, so if I don't get to it:
1. revert / rebase the version change
2. in `src/index.coffee`, line 62, change `@getRangeViewAsync: (designDocumentName, viewName, RangeStart, RangeEnd)` to be `@getRangeViewAsync: (designDocumentName, viewName, rangeStart, rangeEnd)`.

**Comment by frank-dspeed** [comment]
@goatandsheep 
Fixed all errors for you so you can forget about that and soon install new version via npm

**Comment by goatandsheep** [comment]
WOWOW! YOU ARE AWESOME!

**Pull request merged**
